// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TruyenCV.Models;

#nullable disable

namespace TruyenCV.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20251015075103_AddCategoryTypeToComicCategory")]
    partial class AddCategoryTypeToComicCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TruyenCV.Models.Comic", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("bookmark_count")
                        .HasColumnType("integer");

                    b.Property<int>("chapter_count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("embedded_by")
                        .HasColumnType("bigint");

                    b.Property<string>("embedded_from")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("embedded_from_url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("published_year")
                        .HasColumnType("integer");

                    b.Property<float>("rate")
                        .HasColumnType("real");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("embedded_by");

                    b.HasIndex("slug")
                        .IsUnique();

                    b.ToTable("comics");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicCategory", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<int>("category_type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("comic_categories");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicChapter", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<int>("chapter")
                        .HasColumnType("integer");

                    b.Property<long>("comic_id")
                        .HasColumnType("bigint");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("key_require")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("key_require_until")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("comic_id", "chapter")
                        .IsUnique();

                    b.ToTable("comic_chapters");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicComment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("comic_chapter_id")
                        .HasColumnType("bigint");

                    b.Property<long>("comic_id")
                        .HasColumnType("bigint");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_rate")
                        .HasColumnType("boolean");

                    b.Property<int>("like")
                        .HasColumnType("integer");

                    b.Property<int?>("rate_star")
                        .HasColumnType("integer");

                    b.Property<long?>("reply_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("comic_chapter_id");

                    b.HasIndex("comic_id");

                    b.HasIndex("reply_id");

                    b.HasIndex("user_id");

                    b.ToTable("comic_comments");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicHaveCategory", b =>
                {
                    b.Property<long>("comic_id")
                        .HasColumnType("bigint");

                    b.Property<long>("comic_category_id")
                        .HasColumnType("bigint");

                    b.HasKey("comic_id", "comic_category_id");

                    b.HasIndex("comic_category_id");

                    b.HasIndex("comic_id");

                    b.ToTable("comic_have_categories");
                });

            modelBuilder.Entity("TruyenCV.Models.PaymentHistory", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("amount_coin")
                        .HasColumnType("bigint");

                    b.Property<long>("amount_money")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("payment_method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("reference_id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex(new[] { "user_id" }, "IX_PaymentHistory_User");

                    b.ToTable("payment_history");
                });

            modelBuilder.Entity("TruyenCV.Models.RefreshToken", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("revoked_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("token")
                        .IsUnique();

                    b.HasIndex("user_id");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("TruyenCV.Models.Subscription", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("duration_day")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("price_coin")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.ToTable("subscriptions");
                });

            modelBuilder.Entity("TruyenCV.Models.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("avatar")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("banned_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("bookmark_count")
                        .HasColumnType("bigint");

                    b.Property<long>("coin")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("email_verified_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_banned")
                        .HasColumnType("boolean");

                    b.Property<long>("key")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<long>("read_chapter_count")
                        .HasColumnType("bigint");

                    b.Property<long>("read_comic_count")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            avatar = "default_avatar.png",
                            bookmark_count = 0L,
                            coin = 0L,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            email = "ht.kourain@gmail.com",
                            email_verified_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_banned = false,
                            key = 0L,
                            name = "System",
                            password = "$2a$12$4mDXXIMuUV8.QstZN1crHeml7Wbhen1O6QvJ6bXDMJ8z2dHxUnDYi",
                            phone = "0000000000",
                            read_chapter_count = 0L,
                            read_comic_count = 0L,
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 766206485104431104L,
                            avatar = "default_avatar.png",
                            bookmark_count = 0L,
                            coin = 0L,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            email = "maiquyen16503@gmail.com",
                            email_verified_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_banned = false,
                            key = 0L,
                            name = "kourain",
                            password = "$2a$12$Gws/QykY/zHKBnzvvb8lGuFtxmfMPFK0EV9ECV7LBzrQKfA.EiTIe",
                            phone = "0123456789",
                            read_chapter_count = 0L,
                            read_comic_count = 0L,
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TruyenCV.Models.UserUseCoinHistory", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("coin")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("reason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("reference_id")
                        .HasColumnType("bigint");

                    b.Property<string>("reference_type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex(new[] { "user_id" }, "IX_UserUseCoinHistory_User");

                    b.ToTable("user_coin_history");
                });

            modelBuilder.Entity("TruyenCV.Models.UserComicBookmark", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("comic_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("comic_id");

                    b.HasIndex("user_id", "comic_id")
                        .IsUnique();

                    b.HasIndex(new[] { "user_id" }, "IX_UserComicBookmark");

                    b.ToTable("user_comic_bookmarks");
                });

            modelBuilder.Entity("TruyenCV.Models.UserComicReadHistory", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("chapter_id")
                        .HasColumnType("bigint");

                    b.Property<long>("comic_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("comic_id");

                    b.HasIndex("user_id", "comic_id")
                        .IsUnique();

                    b.HasIndex(new[] { "user_id" }, "IX_UserComicReadHistory");

                    b.ToTable("user_comic_read_history");
                });

            modelBuilder.Entity("TruyenCV.Models.UserHasPermission", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("assigned_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("permissions")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("revoke_until")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("revoked_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("assigned_by");

                    b.HasIndex(new[] { "user_id" }, "IX_UserHasPermission");

                    b.ToTable("user_has_permissions");
                });

            modelBuilder.Entity("TruyenCV.Models.UserHasRole", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("assigned_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("revoked_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("assigned_by");

                    b.HasIndex(new[] { "user_id" }, "IX_UserHasRole");

                    b.ToTable("user_has_roles");

                    b.HasData(
                        new
                        {
                            id = 766206486589214720L,
                            assigned_by = 1L,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            role_name = "Admin",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            user_id = 766206485104431104L
                        },
                        new
                        {
                            id = 766206486593409024L,
                            assigned_by = 1L,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            role_name = "User",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            user_id = 766206485104431104L
                        },
                        new
                        {
                            id = 766206486593409025L,
                            assigned_by = 1L,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            role_name = "System",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            user_id = 1L
                        });
                });

            modelBuilder.Entity("TruyenCV.Models.UserHasSubscription", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<bool>("auto_renew")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("end_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("start_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("subscription_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("subscription_id");

                    b.HasIndex("user_id", "subscription_id")
                        .IsUnique();

                    b.ToTable("user_has_subscriptions");
                });

            modelBuilder.Entity("TruyenCV.Models.UserUseKeyHistory", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("chapter_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("key")
                        .HasColumnType("bigint");

                    b.Property<string>("note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("chapter_id");

                    b.HasIndex(new[] { "user_id" }, "IX_UserUseKeyHistory_User");

                    b.ToTable("user_use_key_history");
                });

            modelBuilder.Entity("TruyenCV.Models.Comic", b =>
                {
                    b.HasOne("TruyenCV.Models.User", "EmbeddedByUser")
                        .WithMany()
                        .HasForeignKey("embedded_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmbeddedByUser");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicChapter", b =>
                {
                    b.HasOne("TruyenCV.Models.Comic", "Comic")
                        .WithMany("ComicChapters")
                        .HasForeignKey("comic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicComment", b =>
                {
                    b.HasOne("TruyenCV.Models.ComicChapter", "ComicChapter")
                        .WithMany("ComicComments")
                        .HasForeignKey("comic_chapter_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TruyenCV.Models.Comic", "Comic")
                        .WithMany("ComicComments")
                        .HasForeignKey("comic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.ComicComment", "ReplyTo")
                        .WithMany("Replies")
                        .HasForeignKey("reply_id");

                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("ComicChapter");

                    b.Navigation("ReplyTo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicHaveCategory", b =>
                {
                    b.HasOne("TruyenCV.Models.ComicCategory", "ComicCategory")
                        .WithMany("ComicHaveCategories")
                        .HasForeignKey("comic_category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.Comic", "Comic")
                        .WithMany("ComicHaveCategories")
                        .HasForeignKey("comic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("ComicCategory");
                });

            modelBuilder.Entity("TruyenCV.Models.PaymentHistory", b =>
                {
                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany("PaymentHistories")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.RefreshToken", b =>
                {
                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.UserUseCoinHistory", b =>
                {
                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany("CoinHistories")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.UserComicBookmark", b =>
                {
                    b.HasOne("TruyenCV.Models.Comic", "Comic")
                        .WithMany()
                        .HasForeignKey("comic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.UserComicReadHistory", b =>
                {
                    b.HasOne("TruyenCV.Models.Comic", "Comic")
                        .WithMany()
                        .HasForeignKey("comic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.UserHasPermission", b =>
                {
                    b.HasOne("TruyenCV.Models.User", "AssignedBy")
                        .WithMany("PermissionsAssigned")
                        .HasForeignKey("assigned_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.UserHasRole", b =>
                {
                    b.HasOne("TruyenCV.Models.User", "AssignedBy")
                        .WithMany("RolesAssigned")
                        .HasForeignKey("assigned_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.UserHasSubscription", b =>
                {
                    b.HasOne("TruyenCV.Models.Subscription", "Subscription")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("subscription_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.UserUseKeyHistory", b =>
                {
                    b.HasOne("TruyenCV.Models.ComicChapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("chapter_id");

                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany("KeyHistories")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.Comic", b =>
                {
                    b.Navigation("ComicChapters");

                    b.Navigation("ComicComments");

                    b.Navigation("ComicHaveCategories");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicCategory", b =>
                {
                    b.Navigation("ComicHaveCategories");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicChapter", b =>
                {
                    b.Navigation("ComicComments");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("TruyenCV.Models.Subscription", b =>
                {
                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("TruyenCV.Models.User", b =>
                {
                    b.Navigation("CoinHistories");

                    b.Navigation("KeyHistories");

                    b.Navigation("PaymentHistories");

                    b.Navigation("Permissions");

                    b.Navigation("PermissionsAssigned");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");

                    b.Navigation("RolesAssigned");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
