// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using TruyenCV.Models;

#nullable disable

namespace TruyenCV.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20251106034817_disable auto include")]
    partial class disableautoinclude
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TruyenCV.Models.Comic", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime?>("accept_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("accept_by")
                        .HasColumnType("bigint");

                    b.Property<string>("author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("author_slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("banner_url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("bookmark_count")
                        .HasColumnType("integer");

                    b.Property<int>("chapter_count")
                        .HasColumnType("integer");

                    b.Property<string>("cover_url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("embedded_by")
                        .HasColumnType("bigint");

                    b.Property<string>("embedded_from")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("embedded_from_url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("main_category_id")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("published_year")
                        .HasColumnType("integer");

                    b.Property<float>("rate")
                        .HasColumnType("real");

                    b.Property<Vector>("search_vector")
                        .HasColumnType("vector(256)");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("accept_by");

                    b.HasIndex("embedded_by");

                    b.HasIndex("main_category_id");

                    b.HasIndex("slug")
                        .IsUnique();

                    b.ToTable("comics", t =>
                        {
                            t.HasCheckConstraint("CK_Comic_bookmark_count_Positive", "bookmark_count >= 0");

                            t.HasCheckConstraint("CK_Comic_chapter_count_Positive", "chapter_count >= 0");

                            t.HasCheckConstraint("CK_Comic_main_category_id_Valid", "main_category_id < 2000");
                        });
                });

            modelBuilder.Entity("TruyenCV.Models.ComicCategory", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<int>("category_type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("comic_categories");

                    b.HasData(
                        new
                        {
                            id = 1001L,
                            category_type = 1,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Tiên Hiệp",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 1002L,
                            category_type = 1,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Huyền Huyễn",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 1003L,
                            category_type = 1,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Khoa Huyễn",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 1004L,
                            category_type = 1,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Võng Du",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 1005L,
                            category_type = 1,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Đô Thị",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 1006L,
                            category_type = 1,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Đồng Nhân",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 1007L,
                            category_type = 1,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Dã Sử",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 1008L,
                            category_type = 1,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Cạnh Kỹ",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 1009L,
                            category_type = 1,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Huyền Nghi",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 1010L,
                            category_type = 1,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Kiếm Hiệp",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 1011L,
                            category_type = 1,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Kỳ Ảo",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 1012L,
                            category_type = 1,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Light Novel",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 2001L,
                            category_type = 3,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Điềm Đạm",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 2002L,
                            category_type = 3,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Nhiệt Huyết",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 2003L,
                            category_type = 3,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Vô Sỉ",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 2004L,
                            category_type = 3,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Thiết Huyết",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 2005L,
                            category_type = 3,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Nhẹ Nhàng",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 2006L,
                            category_type = 3,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Cơ Trí",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 2007L,
                            category_type = 3,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Lãnh Khốc",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 2008L,
                            category_type = 3,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Kiêu Ngạo",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 2009L,
                            category_type = 3,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Ngu Ngốc",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 2010L,
                            category_type = 3,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Giảo Hoạt",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3001L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Đông Phương Huyền Huyễn",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3002L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Dị Thế Đại Lục",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3003L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Vương Triều Tranh Bá",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3004L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Cao Võ Thế Giới",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3005L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Tây Phương Kỳ Huyễn",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3006L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Hiện Đại Ma Pháp",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3007L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Hắc Ám Huyễn Tưởng",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3008L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Lịch Sử Thần Thoại",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3009L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Võ Hiệp Huyễn Tưởng",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3010L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Cổ Võ Tương Lai",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3011L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Tu Chân Văn Minh",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3012L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Huyễn Tưởng Tu Tiên",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3013L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Hiện Đại Tu Chân",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3014L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Thần Thoại Tu Chân",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3015L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Cổ Điển Tiên Hiệp",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3016L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Viễn Cổ Hồng Hoang",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3017L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Đô Thị Sinh Hoạt",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3018L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Đô Thị Dị Năng",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3019L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Thanh Xuân Vườn Trường",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3020L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Ngu Nhạc Minh Tinh",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3021L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Thương Chiến Chức Tràng",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3022L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Giá Không Lịch Sử",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3023L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Lịch Sử Quân Sự",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3024L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Dân Gian Truyền Thuyết",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3025L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Lịch Sử Quan Trường",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3026L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Hư Nghĩ Võng Du",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3027L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Du Hí Dị Giới",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3028L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Điện Tử Cạnh Kỹ",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3029L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Thể Dục Cạnh Kỹ",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3030L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Cổ Võ Cơ Giáp",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3031L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Thế Giới Tương Lai",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3032L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Tinh Tế Văn Minh",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3033L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Tiến Hóa Biến Dị",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3034L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Mạt Thế Nguy Cơ",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3035L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Thời Không Xuyên Toa",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3036L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Quỷ Bí Huyền Nghi",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3037L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Kỳ Diệu Thế Giới",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3038L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Trinh Tham Thôi Lý",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3039L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Thám Hiểm Sinh Tồn",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3040L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Cung Vi Trạch Đấu",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3041L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Kinh Thương Chủng Điền",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3042L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Tiên Lữ Kỳ Duyên",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3043L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Hào Môn Thế Gia",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3044L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Dị Tộc Luyến Tình",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3045L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Ma Pháp Huyễn Tình",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3046L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Tinh Tế Luyến Ca",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3047L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Linh Khí Khôi Phục",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3048L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Chư Thiên Vạn Giới",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3049L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Nguyên Sinh Huyễn Tưởng",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3050L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Yêu Đương Thường Ngày",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3051L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Diễn Sinh Đồng Nhân",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3052L,
                            category_type = 2,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Cáo Tiếu Thổ Tào",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4001L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Hệ Thống",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4002L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Lão Gia",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4003L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Bàn Thờ",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4004L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Tùy Thân",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4005L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Phàm Nhân",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4006L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Vô Địch",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4007L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Xuyên Qua",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4008L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Nữ Cường",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4009L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Khế Ước",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4010L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Trọng Sinh",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4011L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Hồng Lâu",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4012L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Học Viện",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4013L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Biến Thân",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4014L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Cổ Ngu",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4015L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Chuyển Thế",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4016L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Xuyên Sách",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4017L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Đàn Xuyên",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4018L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Phế Tài",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4019L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Dưỡng Thành",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4020L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Cơm Mềm",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4021L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Vô Hạn",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4022L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Mary Sue",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4023L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Cá Mặn",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4024L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Xây Dựng Thế Lực",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4025L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Xuyên Nhanh",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4026L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Nữ Phụ",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4027L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Vả Mặt",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4028L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Sảng Văn",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4029L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Xuyên Không",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4030L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Ngọt Sủng",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4031L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Ngự Thú",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4032L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Điền Viên",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4033L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Toàn Dân",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4034L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Mỹ Thực",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4035L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Phản Phái",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4036L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Sau Màn",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4037L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Thiên Tài",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4038L,
                            category_type = 4,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Trò Chơi",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 5001L,
                            category_type = 5,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Góc Nhìn Nam",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 5002L,
                            category_type = 5,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Góc Nhìn Nữ",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TruyenCV.Models.ComicChapter", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<int>("chapter")
                        .HasColumnType("integer");

                    b.Property<long>("comic_id")
                        .HasColumnType("bigint");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("key_require")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("key_require_until")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("comic_id", "chapter")
                        .IsUnique();

                    b.ToTable("comic_chapters");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicComment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("comic_chapter_id")
                        .HasColumnType("bigint");

                    b.Property<long>("comic_id")
                        .HasColumnType("bigint");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_rate")
                        .HasColumnType("boolean");

                    b.Property<int>("like")
                        .HasColumnType("integer");

                    b.Property<int?>("rate_star")
                        .HasColumnType("integer");

                    b.Property<long?>("reply_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("comic_chapter_id");

                    b.HasIndex("comic_id");

                    b.HasIndex("reply_id");

                    b.HasIndex("user_id");

                    b.ToTable("comic_comments", t =>
                        {
                            t.HasCheckConstraint("CK_comic_comments_rate_star_range", "(rate_star IS NULL) OR (rate_star BETWEEN 1 AND 5)");
                        });
                });

            modelBuilder.Entity("TruyenCV.Models.ComicHaveCategory", b =>
                {
                    b.Property<long>("comic_id")
                        .HasColumnType("bigint");

                    b.Property<long>("comic_category_id")
                        .HasColumnType("bigint");

                    b.HasKey("comic_id", "comic_category_id");

                    b.HasIndex("comic_category_id");

                    b.HasIndex("comic_id");

                    b.ToTable("comic_have_categories", t =>
                        {
                            t.HasCheckConstraint("CK_comic_have_categories_comic_category_id", "comic_category_id > 2000");
                        });
                });

            modelBuilder.Entity("TruyenCV.Models.ComicRecommend", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("comic_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("month")
                        .HasColumnType("integer");

                    b.Property<long>("rcm_count")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("year")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("comic_id", "month", "year")
                        .IsUnique();

                    b.ToTable("comic_recommends");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicReport", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("chapter_id")
                        .HasColumnType("bigint");

                    b.Property<long>("comic_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("comment_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("reporter_id")
                        .HasColumnType("bigint");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("chapter_id");

                    b.HasIndex("comment_id");

                    b.HasIndex("reporter_id");

                    b.HasIndex("comic_id", "chapter_id", "comment_id");

                    b.ToTable("comic_reports");
                });

            modelBuilder.Entity("TruyenCV.Models.PaymentHistory", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("amount_coin")
                        .HasColumnType("bigint");

                    b.Property<long>("amount_money")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("payment_method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("reference_id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex(new[] { "user_id" }, "IX_PaymentHistory_User");

                    b.ToTable("payment_history");
                });

            modelBuilder.Entity("TruyenCV.Models.RefreshToken", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("revoked_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("token")
                        .IsUnique();

                    b.HasIndex("user_id");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("TruyenCV.Models.Subscription", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("duration_day")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("price_coin")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.ToTable("subscriptions");
                });

            modelBuilder.Entity("TruyenCV.Models.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("avatar")
                        .IsRequired()
                        .HasMaxLength(15360)
                        .HasColumnType("character varying(15360)");

                    b.Property<DateTime?>("banned_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("bookmark_count")
                        .HasColumnType("bigint");

                    b.Property<long>("coin")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("email_verified_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("firebase_uid")
                        .HasColumnType("text");

                    b.Property<bool>("is_banned")
                        .HasColumnType("boolean");

                    b.Property<long>("key")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<long>("read_chapter_count")
                        .HasColumnType("bigint");

                    b.Property<long>("read_comic_count")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("firebase_uid")
                        .IsUnique();

                    b.ToTable("users", t =>
                        {
                            t.HasCheckConstraint("CK_User_bookmark_count_Positive", "bookmark_count >= 0");

                            t.HasCheckConstraint("CK_User_coin_Positive", "coin >= 0");

                            t.HasCheckConstraint("CK_User_key_Positive", "key >= 0");

                            t.HasCheckConstraint("CK_User_read_chapter_count_Positive", "read_chapter_count >= 0");

                            t.HasCheckConstraint("CK_User_read_comic_count_Positive", "read_comic_count >= 0");
                        });

                    b.HasData(
                        new
                        {
                            id = 1L,
                            avatar = "default_avatar.png",
                            bookmark_count = 0L,
                            coin = 0L,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            email = "ht.kourain@gmail.com",
                            email_verified_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_banned = false,
                            key = 0L,
                            name = "System",
                            password = "$2a$12$2TFakadQVfOIOz1XsDPhkOFBHFFKSzJMtjyUkkIBJokTaRgiY6LJa",
                            phone = "0000000000",
                            read_chapter_count = 0L,
                            read_comic_count = 0L,
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 766206485104431104L,
                            avatar = "default_avatar.png",
                            bookmark_count = 0L,
                            coin = 0L,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            email = "maiquyen16503@gmail.com",
                            email_verified_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_banned = false,
                            key = 0L,
                            name = "kourain",
                            password = "$2a$12$DF.qp7O4zo5G.OIaYOxXouJqIIiUMJ5r/67yqJHi7cjtr7WAkbZnu",
                            phone = "0123456789",
                            read_chapter_count = 0L,
                            read_comic_count = 0L,
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TruyenCV.Models.UserComicBookmark", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("comic_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("comic_id");

                    b.HasIndex("user_id", "comic_id")
                        .IsUnique();

                    b.HasIndex(new[] { "user_id" }, "IX_UserComicBookmark");

                    b.ToTable("user_comic_bookmarks");
                });

            modelBuilder.Entity("TruyenCV.Models.UserComicReadHistory", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("chapter_id")
                        .HasColumnType("bigint");

                    b.Property<long>("comic_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("comic_id");

                    b.HasIndex("user_id", "comic_id")
                        .IsUnique();

                    b.HasIndex(new[] { "user_id" }, "IX_UserComicReadHistory");

                    b.ToTable("user_comic_read_history");
                });

            modelBuilder.Entity("TruyenCV.Models.UserComicRecommend", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("comic_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("month")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.Property<int>("year")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("comic_id");

                    b.HasIndex("user_id", "month", "year")
                        .IsUnique();

                    b.ToTable("user_comic_recommends");
                });

            modelBuilder.Entity("TruyenCV.Models.UserComicUnlockHistory", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("comic_chapter_id")
                        .HasColumnType("bigint");

                    b.Property<long>("comic_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("comic_chapter_id");

                    b.HasIndex("comic_id");

                    b.HasIndex("user_id", "comic_id", "comic_chapter_id")
                        .IsUnique();

                    b.HasIndex(new[] { "user_id" }, "IX_UserComicUnlockHistory");

                    b.ToTable("user_comic_unlock_history");
                });

            modelBuilder.Entity("TruyenCV.Models.UserHasPermission", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("assigned_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("permissions")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("revoke_until")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("revoked_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("assigned_by");

                    b.HasIndex(new[] { "user_id" }, "IX_UserHasPermission");

                    b.ToTable("user_has_permissions");
                });

            modelBuilder.Entity("TruyenCV.Models.UserHasRole", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("assigned_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("revoked_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("assigned_by");

                    b.HasIndex(new[] { "user_id" }, "IX_UserHasRole");

                    b.ToTable("user_has_roles");

                    b.HasData(
                        new
                        {
                            id = 766206486589214720L,
                            assigned_by = 1L,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            role_name = "Admin",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            user_id = 766206485104431104L
                        },
                        new
                        {
                            id = 766206486593409024L,
                            assigned_by = 1L,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            role_name = "User",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            user_id = 766206485104431104L
                        },
                        new
                        {
                            id = 766206486593409025L,
                            assigned_by = 1L,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            role_name = "System",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            user_id = 1L
                        });
                });

            modelBuilder.Entity("TruyenCV.Models.UserHasSubscription", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<bool>("auto_renew")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("end_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("start_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("subscription_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("subscription_id");

                    b.HasIndex("user_id", "subscription_id")
                        .IsUnique();

                    b.ToTable("user_has_subscriptions");
                });

            modelBuilder.Entity("TruyenCV.Models.UserUseCoinHistory", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("coin")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("reason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("reference_id")
                        .HasColumnType("bigint");

                    b.Property<string>("reference_type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex(new[] { "user_id" }, "IX_UserUseCoinHistory_User");

                    b.ToTable("user_use_coin_history");
                });

            modelBuilder.Entity("TruyenCV.Models.UserUseKeyHistory", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("chapter_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("key")
                        .HasColumnType("bigint");

                    b.Property<string>("note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("chapter_id");

                    b.HasIndex(new[] { "user_id" }, "IX_UserUseKeyHistory_User");

                    b.ToTable("user_use_key_history");
                });

            modelBuilder.Entity("TruyenCV.Models.Comic", b =>
                {
                    b.HasOne("TruyenCV.Models.User", "AcceptByUser")
                        .WithMany()
                        .HasForeignKey("accept_by")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TruyenCV.Models.User", "EmbeddedByUser")
                        .WithMany()
                        .HasForeignKey("embedded_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.ComicCategory", "MainCategory")
                        .WithMany()
                        .HasForeignKey("main_category_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcceptByUser");

                    b.Navigation("EmbeddedByUser");

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicChapter", b =>
                {
                    b.HasOne("TruyenCV.Models.Comic", "Comic")
                        .WithMany("ComicChapters")
                        .HasForeignKey("comic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicComment", b =>
                {
                    b.HasOne("TruyenCV.Models.ComicChapter", "ComicChapter")
                        .WithMany("ComicComments")
                        .HasForeignKey("comic_chapter_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TruyenCV.Models.Comic", "Comic")
                        .WithMany("ComicComments")
                        .HasForeignKey("comic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.ComicComment", "ReplyTo")
                        .WithMany("Replies")
                        .HasForeignKey("reply_id");

                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("ComicChapter");

                    b.Navigation("ReplyTo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicHaveCategory", b =>
                {
                    b.HasOne("TruyenCV.Models.ComicCategory", "ComicCategory")
                        .WithMany("ComicHaveCategories")
                        .HasForeignKey("comic_category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.Comic", "Comic")
                        .WithMany("ComicHaveCategories")
                        .HasForeignKey("comic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("ComicCategory");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicRecommend", b =>
                {
                    b.HasOne("TruyenCV.Models.Comic", "Comic")
                        .WithMany()
                        .HasForeignKey("comic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicReport", b =>
                {
                    b.HasOne("TruyenCV.Models.ComicChapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("chapter_id");

                    b.HasOne("TruyenCV.Models.Comic", "Comic")
                        .WithMany()
                        .HasForeignKey("comic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.ComicComment", "Comment")
                        .WithMany()
                        .HasForeignKey("comment_id");

                    b.HasOne("TruyenCV.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("reporter_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Comic");

                    b.Navigation("Comment");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("TruyenCV.Models.PaymentHistory", b =>
                {
                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany("PaymentHistories")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.RefreshToken", b =>
                {
                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.UserComicBookmark", b =>
                {
                    b.HasOne("TruyenCV.Models.Comic", "Comic")
                        .WithMany()
                        .HasForeignKey("comic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.UserComicReadHistory", b =>
                {
                    b.HasOne("TruyenCV.Models.Comic", "Comic")
                        .WithMany()
                        .HasForeignKey("comic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.UserComicRecommend", b =>
                {
                    b.HasOne("TruyenCV.Models.Comic", "Comic")
                        .WithMany()
                        .HasForeignKey("comic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.UserComicUnlockHistory", b =>
                {
                    b.HasOne("TruyenCV.Models.ComicChapter", "ComicChapter")
                        .WithMany()
                        .HasForeignKey("comic_chapter_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.Comic", "Comic")
                        .WithMany()
                        .HasForeignKey("comic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("ComicChapter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.UserHasPermission", b =>
                {
                    b.HasOne("TruyenCV.Models.User", "AssignedBy")
                        .WithMany("PermissionsAssigned")
                        .HasForeignKey("assigned_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.UserHasRole", b =>
                {
                    b.HasOne("TruyenCV.Models.User", "AssignedBy")
                        .WithMany("RolesAssigned")
                        .HasForeignKey("assigned_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.UserHasSubscription", b =>
                {
                    b.HasOne("TruyenCV.Models.Subscription", "Subscription")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("subscription_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.UserUseCoinHistory", b =>
                {
                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany("CoinHistories")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.UserUseKeyHistory", b =>
                {
                    b.HasOne("TruyenCV.Models.ComicChapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("chapter_id");

                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany("KeyHistories")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.Comic", b =>
                {
                    b.Navigation("ComicChapters");

                    b.Navigation("ComicComments");

                    b.Navigation("ComicHaveCategories");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicCategory", b =>
                {
                    b.Navigation("ComicHaveCategories");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicChapter", b =>
                {
                    b.Navigation("ComicComments");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("TruyenCV.Models.Subscription", b =>
                {
                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("TruyenCV.Models.User", b =>
                {
                    b.Navigation("CoinHistories");

                    b.Navigation("KeyHistories");

                    b.Navigation("PaymentHistories");

                    b.Navigation("Permissions");

                    b.Navigation("PermissionsAssigned");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");

                    b.Navigation("RolesAssigned");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
