// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TruyenCV.Models;

#nullable disable

namespace TruyenCV.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TruyenCV.Models.Comic", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("chap_count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("embedded_from")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("embedded_from_url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<float>("rate")
                        .HasColumnType("real");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("id");

                    b.HasIndex("slug")
                        .IsUnique();

                    b.ToTable("comics");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicCategory", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("comic_categories");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicChapter", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<int>("chapter")
                        .HasColumnType("integer");

                    b.Property<long>("comic_id")
                        .HasColumnType("bigint");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("id");

                    b.HasIndex("comic_id", "chapter")
                        .IsUnique();

                    b.ToTable("comic_chapters");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicComment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("comic_chapter_id")
                        .HasColumnType("bigint");

                    b.Property<long>("comic_id")
                        .HasColumnType("bigint");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_rate")
                        .HasColumnType("boolean");

                    b.Property<int>("like")
                        .HasColumnType("integer");

                    b.Property<int?>("rate_star")
                        .HasColumnType("integer");

                    b.Property<long?>("reply_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("comic_chapter_id");

                    b.HasIndex("comic_id");

                    b.HasIndex("id");

                    b.HasIndex("reply_id");

                    b.HasIndex("user_id");

                    b.ToTable("comic_comments");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicHaveCategory", b =>
                {
                    b.Property<long>("comic_id")
                        .HasColumnType("bigint");

                    b.Property<long>("comic_category_id")
                        .HasColumnType("bigint");

                    b.HasKey("comic_id", "comic_category_id");

                    b.HasIndex("comic_category_id");

                    b.HasIndex("comic_id");

                    b.ToTable("comic_have_categories");
                });

            modelBuilder.Entity("TruyenCV.Models.RefreshToken", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("revoked_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("id");

                    b.HasIndex("token")
                        .IsUnique();

                    b.HasIndex("user_id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TruyenCV.Models.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("remember_token")
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = -1L,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            email = "ht.kourain@gmail.com",
                            name = "System",
                            password = "$2a$12$no/pEj.h1swH6xHTpg2aIetBM4aVUdRecIw28M7py2Gr6VcFeR48K",
                            phone = "0000000000",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 1L,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            email = "maiquyen16503@gmail.com",
                            name = "kourain",
                            password = "$2a$12$CBUvVjDrby8apskH4IXVy.7LBAYen1q5WOUNdTtZvCu/b0OaC8S7C",
                            phone = "0123456789",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TruyenCV.Models.UserHasRole", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("assigned_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("assigned_by");

                    b.HasIndex("id");

                    b.HasIndex("user_id");

                    b.ToTable("user_has_roles");

                    b.HasData(
                        new
                        {
                            id = 763741477254725632L,
                            assigned_by = -1L,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            role_name = "Admin",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            user_id = 1L
                        },
                        new
                        {
                            id = 763741477258919936L,
                            assigned_by = -1L,
                            created_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            role_name = "System",
                            updated_at = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            user_id = -1L
                        });
                });

            modelBuilder.Entity("TruyenCV.Models.ComicChapter", b =>
                {
                    b.HasOne("TruyenCV.Models.Comic", "Comic")
                        .WithMany("ComicChapters")
                        .HasForeignKey("comic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicComment", b =>
                {
                    b.HasOne("TruyenCV.Models.ComicChapter", "ComicChapter")
                        .WithMany("ComicComments")
                        .HasForeignKey("comic_chapter_id");

                    b.HasOne("TruyenCV.Models.Comic", "Comic")
                        .WithMany("ComicComments")
                        .HasForeignKey("comic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.ComicComment", "ReplyTo")
                        .WithMany("Replies")
                        .HasForeignKey("reply_id");

                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("ComicChapter");

                    b.Navigation("ReplyTo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicHaveCategory", b =>
                {
                    b.HasOne("TruyenCV.Models.ComicCategory", "ComicCategory")
                        .WithMany("ComicHaveCategories")
                        .HasForeignKey("comic_category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.Comic", "Comic")
                        .WithMany("ComicHaveCategories")
                        .HasForeignKey("comic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("ComicCategory");
                });

            modelBuilder.Entity("TruyenCV.Models.RefreshToken", b =>
                {
                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.UserHasRole", b =>
                {
                    b.HasOne("TruyenCV.Models.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("assigned_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenCV.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenCV.Models.Comic", b =>
                {
                    b.Navigation("ComicChapters");

                    b.Navigation("ComicComments");

                    b.Navigation("ComicHaveCategories");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicCategory", b =>
                {
                    b.Navigation("ComicHaveCategories");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicChapter", b =>
                {
                    b.Navigation("ComicComments");
                });

            modelBuilder.Entity("TruyenCV.Models.ComicComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("TruyenCV.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
